


cc = /Users/yikealo/desktop/stmgcc/gcc-arm-none-eabi-5_4-2016q3/bin/arm-none-eabi-gcc

CFLAGES = --specs=nosys.specs

Hello: /Users/yikealo/Desktop/test/main.cpp
	$(cc) $(CFLAGES) /Users/yikealo/Desktop/test/main.cpp
